### PR TITLE
add user details meanu dropdown

### PR DESCRIPTION
**Pull request by gamesover**
Screenshot from 2020-11-15 04-46-10

Shall we delete `Sign Out` button from update profile page? 

Kindly advice.

Thank you

### CODE REVIEW

**Comment by jadeydi** [comment]
Why you remove the background? and I think bootstrap is a little big=];//

**Comment by jadeydi** [comment]
I think bootstrap is a bit heavy for the little forum, and we should keep the design consistent.

**Comment by gamesover** [comment]
> Why you remove the background? and I think bootstrap is a little big=];//

what `background` do you mean?

**Comment by gamesover** [comment]
> I think bootstrap is a bit heavy for the little forum, and we should keep the design consistent.

yes, it is a concern.

**Comment by jadeydi** [comment]
For your screenshot, the background color is white, and the link is blue?

**Pull request closed without merging**
